title: Mediocre Blog
author: Brian Picciano
email: mediocregopher@gmail.com
description: >-
  A mix of tech, art, travel, and who knows what else.
url: https://blog.mediocregopher.com
repository: https://github.com/mediocregopher/blog.mediocregopher.com
twitter_username: mediocre_gopher
github_username:  mediocregopher
rss: rss
highlighter: rouge

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-relative-links
 - jekyll-sitemap

date_format: "%b %-d, %Y"

img_widths:
    - 500
    - 1000
    - 1500
    - 2000
    - 2500
    - 3000

feed:
  tags: true
